
import React, { useState, useRef, useEffect } from 'react';
import { ChatMessage } from '../types';
import { streamChatResponse, generateImageFromPrompt } from '../services/geminiService';
import { CloseIcon, SendIcon, ImageIcon } from './icons';

interface ChatBotProps {
    isOpen: boolean;
    onClose: () => void;
}

const ChatBot: React.FC<ChatBotProps> = ({ isOpen, onClose }) => {
    const [messages, setMessages] = useState<ChatMessage[]>([
        { id: 'initial', text: 'Hello! Ask me anything about tech, or switch to image mode to create a visual.', sender: 'bot' }
    ]);
    const [input, setInput] = useState('');
    const [mode, setMode] = useState<'chat' | 'image'>('chat');
    const messagesEndRef = useRef<HTMLDivElement>(null);

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    };

    useEffect(scrollToBottom, [messages]);
    
    useEffect(() => {
        if (isOpen) {
            setMessages([ { id: 'initial', text: 'Hello! Ask me anything about tech, or switch to image mode to create a visual.', sender: 'bot' } ]);
        } else {
            setInput('');
            setMode('chat');
        }
    }, [isOpen]);
    
    const handleChat = async () => {
        const userMessage: ChatMessage = { id: Date.now().toString(), text: input, sender: 'user' };
        const botMessageId = (Date.now() + 1).toString();
        const botMessage: ChatMessage = { id: botMessageId, sender: 'bot', isLoading: true };

        setMessages(prev => [...prev, userMessage, botMessage]);
        
        await streamChatResponse(input, (chunk) => {
            setMessages(prev => prev.map(msg => 
                msg.id === botMessageId 
                    ? { ...msg, text: (msg.text || '') + chunk, isLoading: false } 
                    : msg
            ));
        });
    }

    const handleImageGeneration = async () => {
        const userMessage: ChatMessage = { id: Date.now().toString(), text: `Generate an image of: ${input}`, sender: 'user' };
        const botMessageId = (Date.now() + 1).toString();
        const botMessage: ChatMessage = { id: botMessageId, sender: 'bot', isLoading: true };
        
        setMessages(prev => [...prev, userMessage, botMessage]);

        try {
            const imageUrl = await generateImageFromPrompt(input);
             setMessages(prev => prev.map(msg => 
                msg.id === botMessageId 
                    ? { ...msg, imageUrl, isLoading: false } 
                    : msg
            ));
        } catch(error) {
             setMessages(prev => prev.map(msg => 
                msg.id === botMessageId 
                    ? { ...msg, text: error instanceof Error ? error.message : "Image generation failed.", isLoading: false } 
                    : msg
            ));
        }
    }

    const handleSend = async () => {
        if (input.trim() === '') return;
        setInput('');

        if (mode === 'image') {
            await handleImageGeneration();
        } else {
            await handleChat();
        }
    };

    const getPlaceholder = () => {
        switch(mode) {
            case 'image': return 'Describe an image to create...';
            default: return 'Type your message...';
        }
    };

    if (!isOpen) return null;

    return (
        <div className="fixed bottom-24 right-6 w-full max-w-md h-[60vh] z-40 animate-slide-up">
            <div className="bg-brand-surface rounded-lg shadow-2xl flex flex-col h-full border border-brand-primary/30">
                <header className="p-4 border-b border-brand-primary/20 flex justify-between items-center">
                    <h2 className="font-orbitron text-xl text-brand-secondary">AI Assistant</h2>
                    <button onClick={onClose} className="text-brand-text-muted hover:text-brand-primary transition-colors">
                        <CloseIcon />
                    </button>
                </header>
                <div className="flex-grow p-4 overflow-y-auto">
                    {messages.map(msg => (
                        <div key={msg.id} className={`flex mb-4 ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
                            <div className={`max-w-xs md:max-w-sm px-4 py-2 rounded-lg ${msg.sender === 'user' ? 'bg-brand-primary text-white' : 'bg-brand-bg'}`}>
                                {msg.isLoading && <div className="animate-pulse">...</div>}
                                {msg.text && <p className="whitespace-pre-wrap">{msg.text}</p>}
                                {msg.imageUrl && <img src={msg.imageUrl} alt="Generated by AI" className="rounded-lg mt-2" />}
                            </div>
                        </div>
                    ))}
                    <div ref={messagesEndRef} />
                </div>
                <footer className="p-4 border-t border-brand-primary/20">
                    <div className="flex items-center gap-2">
                         <button onClick={() => setMode(m => m === 'image' ? 'chat' : 'image')} className={`p-3 rounded-full hover:bg-opacity-80 transition-colors ${mode === 'image' ? 'bg-brand-secondary text-white' : 'bg-brand-bg text-brand-text-muted'}`} aria-label="Toggle Image Mode">
                            <ImageIcon className="h-5 w-5" />
                        </button>
                        <div className="relative flex-grow">
                             <input
                                type="text"
                                value={input}
                                onChange={(e) => setInput(e.target.value)}
                                onKeyPress={(e) => e.key === 'Enter' && handleSend()}
                                placeholder={getPlaceholder()}
                                className="w-full bg-brand-bg border border-brand-secondary/50 rounded-full py-2 pl-4 pr-12 focus:outline-none focus:border-brand-primary transition-colors text-brand-text"
                            />
                        </div>
                        <button onClick={handleSend} className="bg-brand-primary p-3 rounded-full text-white hover:bg-opacity-80 transition-colors" aria-label="Send Message">
                            <SendIcon />
                        </button>
                    </div>
                </footer>
            </div>
        </div>
    );
};

export default ChatBot;